map('n', '<Leader>gs', ':Git<CR>', { noremap = true })
map('n', '<Leader>gD', ':Gdiff<CR>', { noremap = true })
map('n', '<Leader>gal', ':diffget //2<CR>', { noremap = true })
map('n', '<Leader>gar', ':diffget //3<CR>', { noremap = true })
map('n', '<Leader>gc', ':Git difftool --name-status<CR>', { noremap = true })
map('n', '<Leader>gB', ':Git blame<CR>', { noremap = true })
